# Generated by Django 4.1 on 2023-01-24 19:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='pos',
            options={'verbose_name_plural': 'pos'},
        ),
        migrations.AddField(
            model_name='branch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
