from django.urls import path
from . import views

urlpatterns = [
    path('', views.branchDasboard, name='index'),
    path('branchdash/<str:pk>/', views.dashboard, name='branchdash'),
    path('dashboard/', views.staffDashboard, name='dashboard'),
    path('update_cart/<str:pk>/', views.updateCart, name='update_cart'),
    path('update_quantity/<str:pk>/', views.updateQuantity, name='update_quantity'),
    path('cart/<str:pk>/', views.cart, name='cart'),
    path('completed/', views.sale_complete, name='completed'),
    path('checkout/<str:pk>', views.checkout, name='checkout'),
    path('category_list/', views.category_list, name='category_list'),
    path('category/<str:pk>/', views.category, name='category'),
    path('edit_category/', views.edit_category, name='edit_category'),
    path('reciept/<str:pk>/', views.reciept, name='reciept'),
    path('category_delete/', views.delete_category, name='category_delete'),
    path('branchstore/', views.branchStore, name='branchstore'),
    path('store/<str:pk>', views.store, name='store'),
    path('delete_product/', views.delete_product, name='delete_product'),
    path('sales/', views.sales, name='sales'),
    path('sales<int:pk>/', views.sales, name='sales_single'),
    path('sales_delete/', views.sale_delete, name='sales_delete'),
    path('records/<str:pk>/', views.record, name='records'),
    path('products/', views.product_category, name='products'),
    path('product/<str:pk>/', views.product, name='product'),
    path('edit_product/', views.edit_product, name='edit_product'),
    path('set_reorder/', views.edit_inventory, name='set_reorder'),
    path('inventorys/<str:pk>/', views.inventory_list, name='inventorys'),
    path('branchinv/', views.branchInventory, name='branchinv'),
    path('inventory/<str:pk>/', views.inventory, name='inventory'),
    path('delete_inventory/', views.delete_inventory, name='delete_inventory'),
    path('staff/', views.staffs, name='staff'),
    path('staff_detail/<str:pk>/', views.staff, name='staff_detail'),
    path('edit_staff/', views.edit_staff, name='edit_staff'),
    path('delete_staff/', views.delete_staff, name='delete_staff'),
    path('restock/<str:pk>/', views.restock, name='restock'),
    path('export_sales', views.export_sales_csv, name= 'export_sales'),
    path('export_audit', views.export_audit_csv, name= 'export_audit'),
    path('profitData/<str:pk>/', views.profitData, name='profitData'),
    path('branchaudit/', views.branchAudit, name='branchaudit'),
    path('price_audit/<str:pk>/', views.inventoryAudit, name='price_audit'),
    path('ticket/', views.errorTicket, name='ticket'),
    path('create_ticket/', views.createTicket, name='create_ticket'),
    path('tickets/<str:pk>', views.Ticket, name='tickets'),
    path('branchrep/', views.branchReport, name='branchrep'),
    path('reports/<str:pk>', views.report, name='reports'),
    path('branchcount/', views.branchCount, name='branchcount'),
    path('count/<str:pk>/', views.countView, name='count'),
    path('addcount/', views.addCount, name='addcount'),
    path('productlist/<str:pk>/', views.inventoryView, name='productlist'),
]
# watch out if the value of the variance changes or it is stamped to each date
# what happens when users logs in to another POS and makes sale note: should not be possible
